name = "example"
            database_name = "test"
            database_user = ""
            database_password = ""
            database_host = ""
            database_port = ""
            database_type = "Sqlite"