name = "example"
            database_name = "3"
            database_user = "example-db"
            database_password = ""
            database_host = ""
            database_port = ""
            database_type = "Postgres"