name = "test_project"
            database_name = "test"
            database_user = "postgres"
            database_password = "postgres"
            database_host = "localhost"
            database_port = "5432"
            database_type = "Postgres"