[rustyroad_project]
name = "example-grapesjs"
[database]
database_name = "example_grapesjs"
database_user = "postgres"
database_password = "spike2"
database_host = "localhost"
database_port = "5432"
database_type = "postgres"